# Generated by Django 4.1.4 on 2022-12-21 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 18, 26, 0, 870874)),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 18, 26, 0, 870888)),
        ),
        migrations.AddField(
            model_name='publication',
            name='topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='publications.topic'),
            preserve_default=False,
        ),
    ]
