# Generated by Django 4.1.4 on 2022-12-26 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_processedmediafolder_topic_publication_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedMediaFolder',
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 13, 49, 45, 748710)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 13, 49, 45, 748722)),
        ),
    ]
