# Generated by Django 4.1.4 on 2022-12-26 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 26, 13, 49, 45, 749467))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 12, 26, 13, 49, 45, 749476))),
                ('is_pdf_moved', models.BooleanField(default=False)),
                ('is_image_converted', models.BooleanField(default=False)),
                ('is_audio_converted', models.BooleanField(default=False)),
                ('is_video_converted', models.BooleanField(default=False)),
                ('is_multipage_pdfs_splitted', models.BooleanField(default=False)),
                ('is_name_corrected', models.BooleanField(default=False)),
                ('is_pdf_converted', models.BooleanField(default=False)),
                ('is_video_posters_created', models.BooleanField(default=False)),
                ('is_image_pushed_to_s3', models.BooleanField(default=False)),
                ('is_audio_pushed_to_s3', models.BooleanField(default=False)),
                ('is_video_pushed_to_s3', models.BooleanField(default=False)),
                ('is_multipage_pdf_pushed_to_s3', models.BooleanField(default=False)),
                ('is_singlepage_pdf_pushed_to_s3', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnzippedArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_name', models.CharField(max_length=50)),
            ],
        ),
    ]
